### PR TITLE
calulator implementation

### PR DESCRIPTION
**Pull request by LoZack19**
I'd just like to interject for a moment. What you're refering to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.

Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called Linux, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.

There really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called Linux distributions are really distributions of GNU/Linux!

### CODE REVIEW

**Comment by FrancescoLFM** [comment]
I really appreciate this work, the flow of the program is really well designed:
- prompt
- calulator
- the capaci incident
- Uh
Shawty go jogging every morning (every morning)
And she make me breakfast almost every morning (every morning)
And she take a naked pic' before she leave the door
I be waking up to pics' before a nigga yawning
And every weekend my shawty comin' over (over)
Shawty could Fendi out, but she like Fashion Nova (Nova)
She ain't driving no Camry, she pullin' in a Rover (Rover)
With her hair so curly, I love you, baby
She said, "What you know 'bout love?" (I'll tell you everything)
I got what you need (oh)
Walk up in the store and get what you want (go get it)
You get what you please
We 'bout to get it on, take off them drawers (I said I love you, baby)
It's just you and me
You know what I be on, I'm about to go raw (love you, baby)
'Cause I like what I see
Look, baby, I said I ain't gon' front
You got my heart beating so fast to words I can't pronounce
And I be getting the chills every time I feel your touch
I be looking at the top and girl, it's only us
All I need is your trust
And girl I told you once, don't make me tell you twice
I know you see this print through my pants that I know you like
And yo' ass be looking so fat when it be in them tights
And I'm going straight to the top, so hope you ain't afraid of heights
You always treat me right, for a fact, you never left
Through all the trials and tribulations, always had my best
So here's 55 hunnid, go and get your breasts
Start rubbin' on your butt, start kissing on yo' neck
Hey batter, batter, hey batter, batter
Niggas know I had to swing, I had to make a play
I had to apply the pressure, 'cause you my hidden treasure
I think I'm falling in love
She said, "What you know 'bout love?" (I'll tell you everything)
I got what you need (oh)
Walk up in the store and get what you want (go get it)
You get what you please
We 'bout to get it on, take off them drawers (I said I love you, baby)
It's just you and me
You know what I be on, I'm about to go raw (love you, baby)
'Cause I like what I see (oh)

**Comment by LoZack19** [comment]
I would like to point out that I have nothing to do with the "strage di Capaci". Here is a photo of mine to prove it:
image
Last chance to look at me, Hector

**Comment by FrancescoLFM** [comment]
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line
Look at the code, you clearly can see the "strage di capaci" incident in the line

**Comment by LoZack19** [comment]
> _Walt... seeming sus lately... I think we have an impostor among us. DON'T LIE TO ME WALT! YOU SUSSY BAKA!_ - Hank Schroeder

**Comment by TuxInside18** [comment]
> I'd just like to interject for a moment. What you're refering to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.
> 
> Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called Linux, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.
> 
> There really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called Linux distributions are really distributions of GNU/Linux!

For so many years I held my breath for you
Held under what became the ocean
Struggling to find footing on what became the ocean floor
And now, as I reflect on what became my foundation

Who am I to say the grass was ever greener
Where my own feet struck on the Earth?
And that the fields, they seemed much neater on my side of the fence
And who am I to question why you took the path you took?
And who the fuck am I to open this closed book?

But the pages just keep turning, turning and my pen just won't run dry
But my eyes they won't stop burning and yet you still have no reply

I guess that in a way, it had to be like this
And I guess in a way, I'm glad it turned out like it did
Because I couldn't stand your sight if I ran into you tonight
And if you died, I just don't think I'd have too much to say tonight

Who am I to say the grass was ever greener
Where my own feet struck on the Earth?
And that the fields, they seemed much neater on my side of the fence
And who am I to question why you took the path you took?
And who the fuck am I to open this closed book?

But the pages just keep turning, turning
If you hear this just forget it
If you hear this just forget it
Oh!

"Beating me wouldn't mean anything now, I'm all through"
"All I want is to earn your respect, how am I meant to do that if you won't fight me?"
"Maybe you should've thought of that, before you sucked at being a man your whole life"
"Oh my god, I hate you so much, I just wanna smash your face in"
"Too late, I'm a dead man..."

**Review by TuxInside18 — APPROVED** [review]
As an anti-capitalist calculator it is okay

**Pull request merged**
